#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted
  mapper-locations: classpath:/mapper/**.xml

#使用p6spy需要跟换数据库连接驱动
spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/spring-tx-invalidation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
#  日志级别
logging:
  level:
    cn.cruder.springtxinvalidation: trace
